# Generated by Django 5.0 on 2023-12-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('CZ', 'Cheese'), ('MS', 'Milk Shake'), ('GH', 'Ghee'), ('IC', 'Ice-Cream'), ('PN', 'Paneer'), ('ML', 'Milk'), ('LS', 'Lassi')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.FloatField(),
        ),
    ]
