# Generated by Django 5.0 on 2023-12-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PN', 'Paneer'), ('CZ', 'Cheese'), ('LS', 'Lassi'), ('CR', 'Curd'), ('IC', 'Ice-Cream'), ('ML', 'Milk'), ('GH', 'Ghee'), ('MS', 'Milk Shake')], max_length=2),
        ),
    ]
