# Generated by Django 5.0 on 2023-12-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IC', 'Ice-Cream'), ('LS', 'Lassi'), ('CR', 'Curd'), ('MS', 'Milk Shake'), ('ML', 'Milk'), ('GH', 'Ghee'), ('CZ', 'Cheese'), ('PN', 'Paneer')], max_length=2),
        ),
    ]
