# Generated by Django 5.0 on 2023-12-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MS', 'Milk Shake'), ('GH', 'Ghee'), ('ML', 'Milk'), ('CZ', 'Cheese'), ('PN', 'Paneer'), ('CR', 'Curd'), ('LS', 'Lassi'), ('IC', 'Ice-Cream')], max_length=2),
        ),
    ]
