# Generated by Django 5.0 on 2023-12-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_product_category_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('ML', 'Milk'), ('LS', 'Lassi'), ('PN', 'Paneer'), ('IC', 'Ice-Cream'), ('MS', 'Milk Shake'), ('CZ', 'Cheese'), ('GH', 'Ghee')], max_length=2),
        ),
    ]
