# Generated by Django 5.0 on 2023-12-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_product_category_payment_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GH', 'Ghee'), ('ML', 'Milk'), ('LS', 'Lassi'), ('MS', 'Milk Shake'), ('PN', 'Paneer'), ('IC', 'Ice-Cream'), ('CZ', 'Cheese'), ('CR', 'Curd')], max_length=2),
        ),
    ]
