# Generated by Django 5.0 on 2023-12-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MS', 'Milk Shake'), ('CZ', 'Cheese'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('IC', 'Ice-Cream'), ('ML', 'Milk'), ('LS', 'Lassi'), ('CR', 'Curd')], max_length=2),
        ),
    ]
