# Generated by Django 5.0 on 2023-12-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_payment_razorpay_payment_id_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GH', 'Ghee'), ('IC', 'Ice-Cream'), ('CR', 'Curd'), ('MS', 'Milk Shake'), ('CZ', 'Cheese'), ('LS', 'Lassi'), ('PN', 'Paneer'), ('ML', 'Milk')], max_length=2),
        ),
    ]
