# Generated by Django 5.0 on 2023-12-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_product_category_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GH', 'Ghee'), ('CR', 'Curd'), ('PN', 'Paneer'), ('ML', 'Milk'), ('LS', 'Lassi'), ('CZ', 'Cheese'), ('MS', 'Milk Shake'), ('IC', 'Ice-Cream')], max_length=2),
        ),
    ]
