# Generated by Django 5.0 on 2023-12-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LS', 'Lassi'), ('CZ', 'Cheese'), ('PN', 'Paneer'), ('IC', 'Ice-Cream'), ('MS', 'Milk Shake'), ('CR', 'Curd'), ('GH', 'Ghee'), ('ML', 'Milk')], max_length=2),
        ),
    ]
