# Generated by Django 5.0 on 2023-12-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IC', 'Ice-Cream'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('LS', 'Lassi'), ('MS', 'Milk Shake'), ('CZ', 'Cheese'), ('CR', 'Curd'), ('ML', 'Milk')], max_length=2),
        ),
    ]
