# Generated by Django 5.0 on 2024-01-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IC', 'Ice-Cream'), ('ML', 'Milk'), ('GH', 'Ghee'), ('LS', 'Lassi'), ('CR', 'Curd'), ('MS', 'Milk Shake'), ('CZ', 'Cheese'), ('PN', 'Paneer')], max_length=2),
        ),
    ]
