# Generated by Django 5.0 on 2024-01-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ML', 'Milk'), ('PN', 'Paneer'), ('MS', 'Milk Shake'), ('CZ', 'Cheese'), ('CR', 'Curd'), ('GH', 'Ghee'), ('IC', 'Ice-Cream'), ('LS', 'Lassi')], max_length=2),
        ),
    ]
