# Generated by Django 5.0 on 2024-01-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PN', 'Paneer'), ('CZ', 'Cheese'), ('MS', 'Milk Shake'), ('CR', 'Curd'), ('IC', 'Ice-Cream'), ('LS', 'Lassi'), ('GH', 'Ghee'), ('ML', 'Milk')], max_length=2),
        ),
    ]
