# Generated by Django 5.0 on 2024-01-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MS', 'Milk Shake'), ('ML', 'Milk'), ('PN', 'Paneer'), ('CZ', 'Cheese'), ('LS', 'Lassi'), ('IC', 'Ice-Cream'), ('CR', 'Curd'), ('GH', 'Ghee')], max_length=2),
        ),
    ]
