# Generated by Django 5.0 on 2024-01-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_product_category_delete_productcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IC', 'Ice-Cream'), ('PN', 'Paneer'), ('LS', 'Lassi'), ('CR', 'Curd'), ('CZ', 'Cheese'), ('MS', 'Milk Shake'), ('ML', 'Milk'), ('GH', 'Ghee')], max_length=2),
        ),
    ]
