# Generated by Django 5.0 on 2024-01-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('PN', 'Paneer'), ('LS', 'Lassi'), ('ML', 'Milk'), ('CZ', 'Cheese'), ('IC', 'Ice-Cream'), ('GH', 'Ghee'), ('MS', 'Milk Shake')], max_length=2),
        ),
    ]
