# Generated by Django 5.0 on 2024-01-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufactor_date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='useby_date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GH', 'Ghee'), ('MS', 'Milk Shake'), ('CZ', 'Cheese'), ('LS', 'Lassi'), ('PN', 'Paneer'), ('ML', 'Milk'), ('IC', 'Ice-Cream'), ('CR', 'Curd')], max_length=2),
        ),
    ]
