# Generated by Django 5.0 on 2024-01-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_product_manufactor_date_product_useby_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CZ', 'Cheese'), ('MS', 'Milk Shake'), ('CR', 'Curd'), ('IC', 'Ice-Cream'), ('LS', 'Lassi'), ('ML', 'Milk'), ('GH', 'Ghee'), ('PN', 'Paneer')], max_length=2),
        ),
    ]
