# Generated by Django 5.0 on 2024-01-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_productcategory_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MS', 'Milk Shake'), ('ML', 'Milk'), ('CR', 'Curd'), ('LS', 'Lassi'), ('CZ', 'Cheese'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('IC', 'Ice-Cream')], max_length=2),
        ),
    ]
