# Generated by Django 5.0 on 2024-01-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('GH', 'Ghee'), ('LS', 'Lassi'), ('CZ', 'Cheese'), ('PN', 'Paneer'), ('IC', 'Ice-Cream'), ('MS', 'Milk Shake'), ('ML', 'Milk')], max_length=2),
        ),
    ]
