# Generated by Django 5.0 on 2024-01-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_remove_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LS', 'Lassi'), ('MS', 'Milk Shake'), ('CZ', 'Cheese'), ('PN', 'Paneer'), ('ML', 'Milk'), ('CR', 'Curd'), ('IC', 'Ice-Cream'), ('GH', 'Ghee')], max_length=2),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
