# Generated by Django 5.0 on 2024-01-12 11:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_alter_productcategory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufactor_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='useby_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
