# Generated by Django 5.0 on 2024-01-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_alter_product_manufactor_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufactor_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
