# Generated by Django 5.0 on 2024-01-13 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_remove_productvariation_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_variation',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
    ]
