# Generated by Django 5.0 on 2024-01-15 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_alter_product_discounted_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='package_size',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.productvariation'),
        ),
    ]
