# Generated by Django 5.0 on 2024-01-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_remove_cart_package_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
