# Generated by Django 5.0 on 2024-01-15 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_alter_cart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
    ]
