# Generated by Django 5.0 on 2024-01-17 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_remove_cart_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariation',
            old_name='quantity',
            new_name='size',
        ),
    ]
