# Generated by Django 5.0 on 2024-01-17 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_rename_quantity_productvariation_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariation',
            old_name='size',
            new_name='quantity',
        ),
    ]
